simulation_on: true #do we use SITL simulation for development?

callsign: "VE3SVF" #Your callsign, for SSTV and APRS transmissions

transmitter:
  tx_sstv: true #transmit SSTV?
  tx_aprs: true #transmit APRS?
aprs:
  aprs_packets: 0 #number of APRS packets between SSTV transmissions
  aprs_period: 0 #time in seconds between APRS packets
camera:
  camera_period: 5 #time in seconds between camera captures (note that this does not take into account capture speed)
